version: '3.1'

services:
  jdb-backend:
    restart: unless-stopped
    container_name: jdn-backend
    privileged: true
    ports:
      - 80:80
    image: jdn-backend:2021-06
    volumes: 
        - /Users/tskim/Study/jdn/backend:/var/www/jdn/backend
  jdn-db:
    image: mariadb:10.4
    container_name: jdn-db
    restart: always
    ports:
        - 3306:3306
    volumes:
        - /Users/tskim/var/mysqldb/data:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: jdn1!