"""Initialize worshps entity..

Revision ID: b51185080463
Revises: f570c5acb64c
Create Date: 2021-06-20 21:21:05.914973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b51185080463'
down_revision = 'f570c5acb64c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_worships_title', table_name='worships')
    op.drop_table('worships')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worships',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=90), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('date', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('imamge_url', mysql.TEXT(), nullable=False),
    sa.Column('update_date', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.Column('create_date', mysql.TIMESTAMP(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_worships_title', 'worships', ['title'], unique=False)
    # ### end Alembic commands ###
